name: build

on: [push, pull_request]

jobs:
  prototype-jpeg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Set up Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          echo "::set-env name=PATH::$HOME/.poetry/bin:$PATH"
      - name: Install dependencies
        run: poetry install --no-root

      - name: Lint
        run: |
          poetry run python -m pylint prototype_jpeg/
          poetry run python -m mypy --ignore-missing-import prototype_jpeg/
      - name: Test
        run: poetry run python -m pytest -v